# Generated by Django 4.2 on 2024-02-24 17:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newspaper', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='redactor',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
